### ISSUE TITLE
Hexo-入门篇

### ISSUE THREAD

**Issue by Tomotoes** [Tomotoes/blog#36]
https://tomotoes.com/blog/hexo-introduction/

**Comment by xi-feng** [comment]
大佬  跑不起来啊    报下面这个错能给讲讲不  谢谢

INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
Unhandled rejection TypeError: E:\hexo\themes\tomotoes\layout\layout.ejs:6
    4| <body>
    5|     <%- partial('_partial/loading') %>
 >> 6|     <%- partial('_partial/menu') %>
    7|     <main id="main">
    8|         <%- body %>
    9|         <%- partial('_partial/footer') %>

E:\hexo\themes\tomotoes\layout\_partial\menu.ejs:47
    45|               menuItem = theme.menu2[i];
    46|             %>
 >> 47|               <a class="nav2item" data-title="<%-menuItem.text %>" href="<%- url_for(menuItem.url) %>" <% if(menuItem.target){ %>target="<%- menuItem.target %>"<% } if(menuItem.text){ %>title="<%-menuItem.text %>"<% } %> >
    48|                 <i class="icon icon-lg icon-<%= i %> <%= i %>"></i>
    49|               </a>
    50|           <% } %>

Cannot read property '0' of null
    at Object.urlForHelper (E:\hexo\node_modules\hexo\lib\plugins\helper\url_for.js:6:11)
    at eval (eval at compile (E:\hexo\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:78:17)
    at returnedFn (E:\hexo\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (E:\hexo\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (E:\hexo\node_modules\hexo\lib\theme\view.js:49:23)
    at Object.partial (E:\hexo\node_modules\hexo\lib\plugins\helper\partial.js:38:15)
    at eval (eval at compile (E:\hexo\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:17:17)
    at returnedFn (E:\hexo\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (E:\hexo\node_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (E:\hexo\node_modules\hexo\lib\theme\view.js:30:15)
    at _compiled.then.result (E:\hexo\node_modules\hexo\lib\theme\view.js:41:23)
    at tryCatcher (E:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\hexo\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (E:\hexo\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (E:\hexo\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (E:\hexo\node_modules\bluebird\js\release\promise.js:699:18)
    at _drainQueueStep (E:\hexo\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (E:\hexo\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (E:\hexo\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
